---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "Tiffany Framworkless Web App Frontend"
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: $(name)
      namespace: fma
      labels:
        app: $(name)
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: $(name)
      template:
        metadata:
          labels:
            app: $(name)
          annotations:
            app: $(name)
        spec:
          containers:
            - name: $(name)
              image: "138666658526.dkr.ecr.ap-southeast-2.amazonaws.com/tiffany-frameworkless-basic-web-app-frontend:$(imageTag)"
              ports:
                - containerPort: 80

  - kind: Ingress
    apiVersion: networking.k8s.io/v1beta1
    metadata:
      name: $(name)
      namespace: fma
      labels:
        app: $(name)
      annotations:
        kubernetes.io/tls-acme: "true"
        whitelist-source-range: 59.100.228.148/30,165.228.249.3/32,49.255.232.68/30,203.34.100.0/24,14.203.189.208/30,210.10.213.48/30,111.69.34.208/28,202.50.111.5/32,111.69.51.32/28,202.50.111.0/24,202.56.51.146/32,210.10.223.248/30,49.255.235.66/31,49.255.41.116/30,203.20.70.0/24,124.254.104.108/30,14.203.6.232/30,202.77.54.80/29,3.105.52.160/32,13.210.196.83/32
    spec:
      tls:
        - hosts:
            - $(host)
          secretName: $(name)-tls
      rules:
        - host: $(host)
          http:
            paths:
              - path: /
                backend:
                  serviceName: $(name)
                  servicePort: 80

  - kind: Service
    apiVersion: v1
    metadata:
      name: $(name)
      namespace: fma
      labels:
        app: $(name)
    spec:
      ports:
        - port: 80
          targetPort: 80
      selector:
        app: $(name)
  
parameters:
  - name: "name"
    description: "app name"
    required: true
    parameterType: string
  - name: "imageTag"
    description: "image tag"
    required: true
    parameterType: "string"
  - name: "host"
    description: "ingress hostname"
    required: true
    parameterType: string
